[build-system]
requires = [
    "setuptools>=46.4",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "nordea-analytics-internal"
dynamic = ["version"]
authors = [
    {name = "Nordea Desk Quants and Markets Advisory Tools", email = "E-advisorySupport@nordea.com"},
]
description = "Nordea Analytics Python library"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "GPL-3.0"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: Microsoft :: Windows",
]
dependencies = [
    "pandas>=2,<3.0",
    "requests>=2.20,<3",
    "requests-kerberos>=0.14.0",
    "pyaml>=16.12.0",
    "pip_system_certs",
]

[project.urls]
Homepage = "https://github.com/NordeaOSS/nordea-analytics"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = {attr = "nordea_analytics.__version__"}

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["nordea_analytics"]
omit = ["*\\__main__.py"]


[tool.poetry]
packages = [{include = "nordea_analytics", from = "src"}]

[tool.poetry.group.dev.dependencies]
nox = ">=2025.2.9"
pip-system-certs = ">=4.0"
poetry = ">=2.3"
poetry-plugin-export = ">=1.10"
pygit2 = ">=1.19.1"
pytest = ">=8.0"
requests = ">=2.32.3"
setuptools = ">=76.0.0"
wheel = ">=0.45.1"

[tool.poetry.group.docs.dependencies]
requests = ">=2.23.0, <3.0.0"
matplotlib = ">=3.7.2"
numpy = ">=2.0.2"
pandas = ">=2.3.1"
poetry = ">=2.3.0"
scipy = ">=1.17.1"
sphinx = ">=9.1.0"
sphinx-autoapi = ">=2.0.1"
sphinx-rtd-theme = ">=3.1.0"

[tool.poetry.group.main.dependencies]
pandas = ">=2.2.3, <3.0"
pip-system-certs = ">=4.0"
pyaml = ">=25.0.0"
requests = ">=2.32.3"
requests-kerberos = ">=0.15.0"

[[tool.poetry.source]]
name = "numpy"
url = "https://[USERID]:[TOKEN]]@artifactory.oneadr.net/artifactory/api/pypi/remote-pypi/simple"
priority = "primary"

[[tool.poetry.source]]
name = "matplotlib"
url = "https://[USERID]:[TOKEN]]@artifactory.oneadr.net/artifactory/api/pypi/remote-pypi/simple"
priority = "primary"

[[tool.poetry.source]]
name = "pandas"
url = "https://[USERID]:[TOKEN]]@artifactory.oneadr.net/artifactory/api/pypi/remote-pypi/simple"
priority = "primary"

[[tool.poetry.source]]
name = "scipy"
url = "https://[USERID]:[TOKEN]]@artifactory.oneadr.net/artifactory/api/pypi/remote-pypi/simple"
priority = "primary"

[[tool.poetry.source]]
name = "setuptools"
url = "https://[USERID]:[TOKEN]]@artifactory.oneadr.net/artifactory/api/pypi/remote-pypi/simple"
priority = "primary"

[[tool.poetry.source]]
name = "sphinx"
url = "https://[USERID]:[TOKEN]]@artifactory.oneadr.net/artifactory/api/pypi/remote-pypi/simple"
priority = "primary"

[[tool.poetry.source]]
name = "sphinx-autoapi"
url = "https://[USERID]:[TOKEN]]@artifactory.oneadr.net/artifactory/api/pypi/remote-pypi/simple"
priority = "primary"

[[tool.poetry.source]]
name = "sphinx-rtd-theme"
url = "https://[USERID]:[TOKEN]]@artifactory.oneadr.net/artifactory/api/pypi/remote-pypi/simple"
priority = "primary"
